### ISSUE TITLE
Positioning

### ISSUE THREAD

**Issue by narcolepticinsomniac** [schomery/youtube-hover#1]
Even with it being adjustable, which is cool, positioning is kinda jenky. User defined y coordinates are still relative to the cursor, so the player appears cut off if links are hover toward the top or bottom of the screen.

The only reason the positioning had to be relative to the mouse in the other extension, is because the player itself interfered with the link hover. If it tried to appear where you were hovering, the iframe would blink in and out as the two fought for focus.

Yours doesn't have that issue. I see no reason why it couldn't default to the vertical and horizontal center of the viewport. Leaving the user-defined margins to play with positioning from center would be sweet.

As I mentioned, I changed positioning to "fixed" and I quite like it. Having a touch of ADD, it's nice to have the video stay and still be able to scroll around. Probably not for everybody, but a toggle option would be nice.

Btw, I'm fairly certain I could achieve most of this with a userstyle overriding the CSS, but I think these tweaks would make it much better out of the box.

**Comment by schomery** [comment]
> so the player appears cut off if links are hover toward the top or bottom of the screen.

This is fixed

> I see no reason why it couldn't default to the vertical and horizontal center of the viewport

The latest dev supports two different modes. Please give it a try

**Comment by narcolepticinsomniac** [comment]
The center mode is pretty perfect as is. It'd be even better if you could still adjust px's _from_ the center. I know with pure CSS, you'd have to set top/bottom/left/right to 0 and margin to auto, so maybe that's not realistic, even with javascript. If you could make it adjustable from the center, I don't see why you'd need the other mode. Setting it to the mouse would always need to default towards the middle anyway to not go off the edges.

I don't plan to use it, but I'd be a dick if I didn't test the other mode. It still seems pretty buggy. I have a low-res at 1366x768, and a 600px width video is often off the screen in every direction. I made screen record and noted the settings at the beginning.
[Youhover.zip](https://github.com/schomery/youtube-hover/files/660969/Youhover.zip)

**Comment by schomery** [comment]
Thanks. It should have been fixed on the latest dev.

**Comment by narcolepticinsomniac** [comment]
Any chance the margin tweaks can also be applicable to the "center mode"? I see you're using a calc on "top" and "left", so the margins should still be manipulable by the user.

**Comment by schomery** [comment]
To have x/y offset from the center of the screen?

**Comment by narcolepticinsomniac** [comment]
Yeah, starting from the centered position. Again, since you're not using the margin property, they could be applied in a userstyle, but it'd be cool if the offsets worked in the settings.

**Comment by schomery** [comment]
>  since you're not using the margin property

You mean the `calc` method is not working properly?

**Comment by narcolepticinsomniac** [comment]
No, the calc is fine. 50% - 1/2 the width/height centers perfectly. I was hoping the offsets could still be functional, being applied from the center positioning. My width is 1366px, the player is 600px. X-coordinates + 383px would  move it to the far right, - 383px to the far left. Same with Y to move it up or down.

On a separate positioning issue, to me, the "Relative to link mode" is still wonky. It's better so far as it's not way off horizontally, but hovering links toward the bottom of the page still results in the player appearing off the bottom of the viewport. I don't plan to use it, but it is still the default. No matter where on a page a link is hovered, the player should always remain in the viewport. Imagus does a nice job with that, and I think the code is at the top in ...imagus\includes\content.

**Comment by schomery** [comment]
Okay then we have x/y offset for both modes now.

**Comment by narcolepticinsomniac** [comment]
Center mode is perfect now. Can't thank you enough for that. I'm obviously biased, but I'd make that the default. 

To me, "relative mode" could never get the positioning right without appearing partially off the top or bottom of the screen when hovering links toward the top or bottom. The only way to make sure the whole video is always entirely in the viewport would be to take the offsets away from relative mode, and do some calculation magic so that whatever part of the player necessary, appears closest to the mouse leaving enough room for it to remain in the viewport. If hovering a link in the upper left corner, the upper left corner of the player would be relative to the mouse.  If hovering a link in the bottom left corner, the bottom left corner of the player would be relative to the mouse. Basically all four edges would have to correlate to the counterpart of the screen position of the mouse. On top of that you'd need to calculate the viewport height with the height of the player for vertical positioning. This makes my brain hurt. Imagus does do this, so perhaps you could take a look at how they're doing it.

I don't plan on using it, so I'm just trying to be helpful. I know with the default settings, the player was rendering off-screen frequently which would drive me nuts, and I don't think it's the best first impression considering how cool this extension really is.

For the technically challenged, you may want to label the offsets "horizontal" and "vertical". You also might "fool-proof" the sizing and margin offsets with some max-limit calcs.

Player could be done with CSS:

`max-height: calc(100vh - 30px)!important;
max-width: calc(((100vh - 30px) * 16) / 9)!important;`

Margins may be trickier. Just a thought.

**Comment by schomery** [comment]
The new dev should have fixed all the issues of relative mode. Give it a try.

**Comment by narcolepticinsomniac** [comment]
I hate to say it, but relative mode looks the same (player off the bottom of the screen). I made a screen record and noted the settings in it:
[YT-H.zip](https://github.com/schomery/youtube-hover/files/666403/YT-H.zip)

To reiterate, I'm very happy with the other mode, so I don't wanna come across like I'm complaining, but if you want me to test for bugs, I'm more than happy to. You've been so cool, it's the least I can do. In fact, if you ever need someone to test anything, just say so here and I'll get a notification.

If you make any changes today, I'll test it when I get home from work. If not, tomorrow morning or whenever.

**Comment by schomery** [comment]
I appreciate your feedback. It is going to make this extension more useful for all users.

So we have two options. Either adjust the positioning of the player such that it keeps itself in the viewport or scroll the viewport such that the player is inside the viewport.

I personally don't like the first one since the player is going to overlap with the opener link. The second method is implemented but it is not active by default. I am not 100% sure that this method works on all pages!

**Comment by narcolepticinsomniac** [comment]
Forcing a scroll never occurred to me. It's a good solution and I would enable it by default. I tested on a handful of sites and it worked well. I still prefer the other mode, but I'd definitely use "relative" now. I will say that the scroll is a little jarring, even when you're expecting it. If the transition could be a little slicker, that'd be nice, but it's fine as it is. Very nicely done.

**Comment by schomery** [comment]
> If the transition could be a little slicker, that'd be nice, but it's fine as it is.

Smooth scrolling is implemented and is enabled by default. Please give this feature a try in different websites to make sure we can have it enabled by default in the production version.

btw, if you prefer the center mode, the new "Turn off the light" feature looks good in this mode.

**Comment by narcolepticinsomniac** [comment]
Nice. Seems smoother. No problems with it so far either. I think you nailed it. 

"Turn off the lights" is nice too. I'm currently liking the player tucked in the lower right corner so I can still browse around while videos play. I probably won't use Nightmode much, but its a cool feature and works well.
