### ISSUE TITLE
Some videos don't autoplay

### ISSUE THREAD

**Issue by narcolepticinsomniac** [schomery/youtube-hover#12]
I thought autoplay was forced, but some don't, for example:

https://youtu.be/WukPAFHYE80?t=34

Edit: Apparently Github won't allow embedding with their cross-domain security policy? Weird thing is, I remember posting test links that worked here before. Anyway here's the Reddit page:
https://www.reddit.com/r/videos/comments/5u7oyy/military_helicopter_pilot_asking_a_trucker_for/

**Comment by schomery** [comment]
Thanks! it is fixed now

**Comment by narcolepticinsomniac** [comment]
Also seems good, thanks!
