### ISSUE TITLE
[Feature request] Allow Esc to close the hover window

### ISSUE THREAD

**Issue by mismjames** [schomery/youtube-hover#13]
Right now I have to click outside the hover window to close it.  I'd rather just hit Esc like with Imagus and other hovering extensions.  Clicking in the dark also can sometimes cause an inadvertent link to be clicked on (ideally you should capture that click and ignore it).

**Comment by schomery** [comment]
Thanks for the suggestion. `Esc` is now supported.

> ideally you should capture that click and ignore it

This is fixed as well.
