### ISSUE TITLE
Errors in the console

### ISSUE THREAD

**Issue by narcolepticinsomniac** [schomery/youtube-hover#19]
Seeing them a lot recently when looking for other stuff:

![ytohp](https://user-images.githubusercontent.com/14100003/28458168-bd6b9442-6dd6-11e7-8fd3-9a585aafec09.png)

**Comment by schomery** [comment]
Anyway to reproduce this?

**Comment by narcolepticinsomniac** [comment]
Didn't think it needed any detailed steps. It happens everywhere. Tested in a clean profile. Open devtools and load a page. Mouse around/scroll and you should see the same errors, I would think.

**Comment by schomery** [comment]
@narcolepticinsomniac please double-check the recently closed issues. If everything is working as expected, I'll submit this new version.

**Comment by narcolepticinsomniac** [comment]
Everything seems fixed and very much improved all around. Appreciate it.

**Comment by schomery** [comment]
Perfect!
