### ISSUE TITLE
Add links to cache?

### ISSUE THREAD

**Issue by narcolepticinsomniac** [schomery/youtube-hover#4]
If possible to distinguish visited links.

**Comment by schomery** [comment]
This issue is unclear

**Comment by narcolepticinsomniac** [comment]
When you hover a link and the link is loaded to the iframe, could't it be added to the browser cache so the link changes to a :visited state/color. Imagus is the counterpart for images and even some video sites (not Youtube) and it does this.

**Comment by schomery** [comment]
To the best of my knowledge, marking a cross origin link as visited violates user privacy, and hence it is not possible. If you have seen this anywhere I would like to take a look at their implantation.  Though it is possible to *temporary* change a CSS attribute at least until the page gets refreshed. The latest dev add a text decoration to the previewed links.

**Comment by narcolepticinsomniac** [comment]
The strikethrough is a novelty, but yeah, doesn't survive a reload. Like I mentioned, Imagus does this. Here's their .crx. You'd know better what to look for,
[imagus.zip](https://github.com/schomery/youtube-hover/files/661183/imagus.zip)

**Comment by narcolepticinsomniac** [comment]
I tried investigating how Imagus handles videos like: https://www.reddit.com/r/streamables/comments/2ylbt4/those_fishes_are_so_huge_they_are_like_the_size/
but they're not easy to inspect since they only appear when you're actively hovering the link. Knowing very little about what I'm talking about, my best guess is that they're not using iframes (ajax maybe), so the cross-domain privacy issue doesn't apply.

Links turning to visited would be nice, but it isn't the biggest deal in the world if it's a headache. 

I'll be away from my computer for a bit, but if you make any updates, I'll check them out when I get home. Thanks Schomery.

**Comment by schomery** [comment]
Okay got this fixed. Give the latest dev a try. The link will be added to history and also we are going to have the strike-through. I think this strike-through decoration is easier to catch.

**Comment by narcolepticinsomniac** [comment]
Great work! I'm sure my wild speculation was no help, but you got it working with the iframe anyway. That's awesome. 

I can't seem to get the strikethrough toggle to work now though. All I really wanted was for them to be added to history, so they change color. That way, you can easily distinguish vids you've already viewed, even from past sessions. Strikethrough is redundant, and I never particularly liked the look of it, so I toggled it off, but it's still on.

**Comment by schomery** [comment]
> so I toggled it off, but it's still on.

This is now fixed. I added two different options. You can have either or both strike-through and add to history.

**Comment by narcolepticinsomniac** [comment]
> This is now fixed.

Yup, awesome.

 I was showing a friend online and the first thing she said was that the strikethrough was cool. I'm not a fan, but it she loved it, so...cool option.
