### ISSUE TITLE
Hover delay isn't functioning as expected.

### ISSUE THREAD

**Issue by narcolepticinsomniac** [schomery/youtube-hover#5]
The idea was that setting a delay of a second would allow you to quickly hover over a link without the video being called to load, to rule out inadvertent mouse-overs. When quickly mousing over a link with a two second delay set, the video is still called immediately. The delay seems to be applied to when it shows up instead, i.e. mouse quickly over a link and two seconds later the vid shows up. I demonstrated in the video I just attached at the end of it with some quick hovers.

**Comment by schomery** [comment]
This should have been fixed on the latest dev.
