### ISSUE TITLE
Loading gif is a resource drain

### ISSUE THREAD

**Issue by narcolepticinsomniac** [schomery/youtube-hover#7]
When I first tested "Turn off the lights" it wasn't working. I remembered that I made a userstyle for the iframe. I gave it a black background and lightgray box-shadow. You're doing the "lights off" with box-shadow, so mine was overriding it. The code I was using was:

```
.ihvyoutube{
background:hsla(0,0%,0%,.95)!important;
box-shadow:hsla(0,0%,40%,.9) 1px 1px 5px!important;}
```

I had made the conscious decision to use background instead of background-color because I've run into a lot of loading gifs that constantly waste CPU in the background. Anyway, while fixing the style to:

```
.ihvyoutube{background:hsla(0,0%,0%,.95)!important;}

.ihvyoutube:not([data-dark="true"]){box-shadow:hsla(0,0%,40%,.9) 1px 1px 5px!important;}
```
I figured I'd check using background-color instead. I have a fairly old lower-end AMD quad, probably the equivalent of an i3 if I had to guess. The gif uses about 20% CPU the entire time the iframe is present, which is more than the videos use on their own.

The gif is a pretty cool looking one, so instead of changing it, maybe just remove it once it's no longer visible?

**Comment by narcolepticinsomniac** [comment]
Oh, I just switched off Nightmode and you're using different gifs. The default one doesn't work on the black I'm using. Now that I think of it, that's why I removed it. I debated putting a different one in and decided it probably wouldn't be worth it to leave it running in the background. It isn't.

The default loading gif uses a little less than half the CPU as the nightmode gif. Still unnecessary to keep running in the background though. The Nightmode gif is cooler looking, maybe use an inverted version as the default (or just make the default background color black).

**Comment by schomery** [comment]
Nice catch! 

The only issue we have is that we don't know when the player is actually ready so that the gif can gets unloaded. Normally it is possible to listen for YouTube's `onReady` event, but since we are under a proxy, it is pretty complex to get these DOM events. For now I just listen for iframe's `load` event and unload the gif after 10 seconds.
https://github.com/schomery/youtube-hover/blob/master/src/data/inject/index.js#L67-L69

Although this is not a prefect solution, still better than not unloading the gif

**Comment by narcolepticinsomniac** [comment]
Your solution is good. It doesn't need to be "perfect". The timing is accurate, and removing it at all is more considerate than most designers these days. My computer isn't the most powerful, and when the fan goes, I don't just junk the laptop, I replace the fan. I think it's on its 4th fan. Fans are cheap, but replacing them in laptops isn't the easiest task. Because of this, I monitor CPU and temp in the system tray with CoreTemp. I know the normal ranges for things and usually notice if something is out of whack pretty quickly.

I also like the black background and the cooler looking loading gif being the default. Good decision. 

Unless not doing it "perfectly" is gonna bug you, I'd say this one is resolved. Thanks.

**Comment by narcolepticinsomniac** [comment]
Hey, off-topic, but somewhat related question. Is there a javascript solution to forcing a pre-buffer limit on html5 videos? Chrome usually does this by default, but one site in particular, vk.com, recently changed something that is making videos speed buffer the entire video. The increase in CPU is ludicrous.

I've even tried in Firefox where there's an about:config setting for setting a hard media readahead limit. It works well for other sites, but not on VK either. 

Maybe you know some generic code I could try in a userscript. To actually play videos there, I think you have to be a member. I'd also happily let you use my logon if you were inclined to take a look.

More than anything, I'd like to know if you think it's possible. If so, I could always keep asking around till someone takes pity on my poor CPU.

**Comment by schomery** [comment]
Well, you need to find a way to pretend `<source>` element is not supported in this browser; https://developer.mozilla.org/en-US/docs/Web/HTML/Element/source

Does https://addons.mozilla.org/en-US/firefox/addon/youtube-without-dash-playback/ work with vk.com?

**Comment by schomery** [comment]
more info https://developer.mozilla.org/en-US/docs/Web/HTML/DASH_Adaptive_Streaming_for_HTML_5_Video

**Comment by narcolepticinsomniac** [comment]
In regard to VK, I was just investigating last night, and while it is force buffering faster than most, I don't think that's what's actually wasting CPU. The site is heavy on javascript, and I think it's a bug that some script keeps looping instead of releasing. One involved in calling/displaying videos I'd have to guess. 

I can hide the entire container div that appears when a video link is clicked, so no video is present or therefore decoding, and if a video link is clicked, CPU skyrockets (bouncing between 10%-30%) the entire time the "overlay" is present. Close it, and it stops. To put that in perspective, a typical 720p vid bounces between 5%-15%.

**Comment by narcolepticinsomniac** [comment]
After investigating some more, and checking out the sources you referenced, it does appear to me that DASH has something to do with it. It'd have to be really poorly implemented, no? Youtube uses it and their videos are pretty efficient on resources. 

From what I'm gathering (probably not much), DASH is what segments videos? 

> Does https://addons.mozilla.org/en-US/firefox/addon/youtube-without-dash-playback/ work with vk.com?

Yes it does seem to alter the default playback mechanism. Without it enabled, in the "Network" tab, I can see constant calls for video segments which are returned and loaded. With it enabled this doesn't happen. Videos still start off consuming a lot of CPU, but after about a minute and a half, it actually leveled off to 15%-20% for the most part. Still high, but nowhere near as bad.

It still had consistent spikes, which seemed to be coming from whatever script was still executing. There wasn't constant segments loading in "Network", but there was still frequent requests being made:
https://queuev4.vk.com/im731
https://vk.com/al_video.php?act=a_view_segments

I think it sheds a little light about how they've turned their player into garbage (it used to work fine), but even that extension doesn't fix it all that well, and I don't use Firefox at all regularly anyway.

**Comment by schomery** [comment]
Have you tried to use FLASH player instead? Flash might work on lower CPU compared to HTML5 player. I know that there are some extensions that you can use to force Flash over the default HTML5 like this browser is not supporting HTML5 video element.

**Comment by narcolepticinsomniac** [comment]
It's pretty bad when Flash is being regarded as the more efficient option. They always defaulted to Flash up until about 4-6 months ago. I usually have it disabled, and their html5 player was a little heavier than most, but really decent. It's when they reworked it to make it the default that it turned to garbage. I don't know if there is a fix, other than not watching videos there.

**Comment by narcolepticinsomniac** [comment]
Hey Jeremy, I finally figured out a hack to fix the wasteful VK html5 player. I experimented with trying to spoof the UA string to force Chrome's native html5 player. Unfortunately, spoofing the UA for VK entirely, causes it to redirect to a separate mobile version of their site. Not only is the mobile layout horrible on a PC, but many features and functionality are absent or broken.

After testing many UA switching extensions, I  finally came across [this one](https://chrome.google.com/webstore/detail/ljfpjnehmoiabkefmnjegmpdddgcdnpo?hl=en-us). It's not exactly what I'd call "user friendly", but it has a lot of cool advanced features not available in other similar extensions. Mainly, you can target very specific requests on very specific URLs via regex.

After installing, in the extension popup dropdown menu, you select "Activate Now" (leave the default set to "Default (Current Chrome)"), click "Enable pattern" and "Enable URL sniffer", and then click "Options".

On the options page, highlight and copy the iPAD UA string, then scroll down to the "User pattern" section. Delete the example for Google (it works and it sucks). 

In the "Pattern" field, enter `r/^https?://(.*)?vk\.com/al_video\.php.*/*`, then select "xmlhttprequest", then in the "User Agent string" field, paste the iPAD UA string you copied from above. Save, and you're done.

All calls to load videos are to URLs included in the regex. It spoofs a mobile UA for those calls only. The result is that videos load in the native Chrome player.

One other tweak I made was for quality. Chrome's native player automatically defaults to the highest quality available. For VK, that often means 1080p. I'm fine with 720p, and their 1080p's are not only larger, but less compressed, so they're typically more than double the size of the 720p. This results in slightly higher resource usage and choppier playback. To default to 720p, I simply applied an Adbock filter for 1080p: `||vk.me/*1080.mp4`. Chrome automatically loads the next highest available, which is 720p.

VK's player was ridiculous. With most 720p streams, CPU usage bounces around between 5%-15%. Their player was like 5x that, often bouncing around between 40%-60%. This hack, forcing the native html5 player and setting the quality to 720p, results in typical CPU utilization of 5%-15%. Playback is also smoother, and skipping around in the timeline is quicker and more responsive. As an added bonus, VK has autoplaying videos everywhere, which can't be set to not autoplay. With the native player, these videos are all still available, but the annoying autoplay "feature" is disabled.

I figured I'd fill you in, and I got specific with the instructions in case anyone happens to come across this while looking for a solution.
