### ISSUE TITLE
Link parsing issues.

### ISSUE THREAD

**Issue by narcolepticinsomniac** [schomery/youtube-hover#8]
I've run into it a handful of times, where random links fail. One time there were a few right next to each other and only one didn't work. When I reloaded the page, it worked. 

It also craps out after a while with infinite scrolling. Using RES on reddit, around comment 300, on "page 10" of the infinite scroll, it stopped working altogether.

I think Chrome (maybe FF as well) has issues with document start. The Tampermonkey dev has been lobbying for a resolution to earlier script injection. Not sure if that is the culprit here or not. Anyway, I was having issues with a script not too far back and a friend fixed it by running a "double check" with the mutation handler. It's the same one I posted in a previous issue. I'm not good with javascript, but I can tell you this method is fast and doesn't miss.

```
// ==UserScript==//
// @name        Test
// @version     1.0
// @include     [link removed]/*
// @run-at      document-start
// @require     https://greasyfork.org/scripts/12228/code/setMutationHandler.js
// ==/UserScript==

// process the already loaded portion of the page
process(document.querySelectorAll(
    'a'
));

// process the stuff loaded from now on
setMutationHandler(
    document,
    'a',
    process
);

function process(nodes) {
    for (var i=0, n; (n=nodes[i++]); ) {
        if (n.textContent.match(/wacka-wacka/i)) {
            (n.closest('.item') || n.parentNode).remove();
        }
    }
}
```

**Comment by narcolepticinsomniac** [comment]
Happy holidays, btw.

**Comment by schomery** [comment]
Happy holidays to you too!

> It also craps out after a while with infinite scrolling. Using RES on reddit, around comment 300, on "page 10" of the infinite scroll, it stopped working altogether.

Are you sure the player was not open somewhere top? I am not able to reproduce this. Around comment 600, it is still working fine for me when RES is installed.

**Comment by narcolepticinsomniac** [comment]
I'm sure it wasn't open. It's not really something I could give you steps to repro either. Happened again yesterday at around comment 100. The only thing I could say is that I'm leaving that page for a while pretty frequently and then coming back to it after a while. Not that it should matter.

Like I mentioned though, I've seen it miss random links elsewhere on regular old pages as well. Reload, and it works.. It doesn't happen often, but it is missing random links occasionally.

**Comment by narcolepticinsomniac** [comment]
As I mentioned, in Chrome at least, document-start is not guaranteed. Not yet anyway, it is currently flawed. I had scripts that never had issues before, that had to be readjusted for recent versions of Chrome. Elements loading before "document-start" needed to be accounted for. Maybe they've improved speed by fractions of a second recently, but they are beating their own document-start API. Don't know for sure that's the issue here, but it's a good possibility.

**Comment by narcolepticinsomniac** [comment]
Related: https://bugs.chromium.org/p/chromium/issues/detail?id=471801

**Comment by schomery** [comment]
In this extension we only add two event listeners on document-start, [L151](https://github.com/schomery/youtube-hover/blob/master/src/data/inject/index.js#L151) and [L206](https://github.com/schomery/youtube-hover/blob/master/src/data/inject/index.js#L206). We do not create any new elements until the first listener actually detects hovering over a YouTube link.

Two things may go wrong

1. These listeners get somehow suspended
2. For some reason [the injected iframe element](https://github.com/schomery/youtube-hover/blob/master/src/data/inject/index.js#L3) is dead, but the extension thinks it is still there.  If so, it is going to skip link checking per [L157](https://github.com/schomery/youtube-hover/blob/master/src/data/inject/index.js#L157)

If you are on a local version, you can set console logs for these two events and when the extension is not working, check the console to see which one is not firing. Also in the inspector window, you can change the context to this extension and see if the `iframe` variable is set with a dead object.

**Comment by narcolepticinsomniac** [comment]
I know how to look at the console. Using it effectively is a little different. It did quit working on Reddit again today. I can't even recreate it when I try. There was an error. I took a couple screenshots in case they're insightful.

![chrome_2016-12-27_18-00-23](https://cloud.githubusercontent.com/assets/14100003/21510907/5f64f9e4-cc67-11e6-922f-d88b1267b183.png)
![chrome_2016-12-27_18-01-24](https://cloud.githubusercontent.com/assets/14100003/21510911/6864d366-cc67-11e6-8b96-3d567fd8fcf4.png)
![cns22b](https://cloud.githubusercontent.com/assets/14100003/21510917/84c74c14-cc67-11e6-8703-6874cfc58eb2.png)

The last one is just to see if I can get my favicon to change if it's hosted here.

**Comment by narcolepticinsomniac** [comment]
Ah! The favicon will change if it's not cross domain.

**Comment by schomery** [comment]
I see, this one occurs if iframe gets unloaded before loading is complete. Got it fixed, thanks. Still this one cannot be the reason why the extension stops working altogether. We somehow need to find away to reproduce it.

**Comment by narcolepticinsomniac** [comment]
The one common denominator for Reddit is time. I just went back to reddit's front page which had been opened in a background tab for a while. The extension had stopped working. Try opening a tab and leaving it in the background for a long while.

**Comment by narcolepticinsomniac** [comment]
When it quit working on Reddit again today, I checked out the console, and there does seem to be related errors. When I clear the console and scroll down for another infinite scroll page to load, I get these errors that seem to correlate to the number of YT links:
![chrome_2016-12-29_20-38-11](https://cloud.githubusercontent.com/assets/14100003/21558435/fbc943b6-ce07-11e6-978a-26203b2da5a1.png)
Not sure why, or if it's even your extension causing it, but perhaps it's insightful.

**Comment by schomery** [comment]
This means a resource from YouTube player cannot be accessed. It might be from inside of the iframe. If so it means the iframe is still open, or maybe it is not from this extension.

Whenever it happens, please open the console, switch to the extension context and type `iframe` to see if the variable is set or not
![screen shot 2017-01-02 at 17 19 53](https://cloud.githubusercontent.com/assets/11704051/21590287/ba9c2358-d10f-11e6-83bf-e92dace508aa.png)

if it was set then type `iframe = null` and see if the extension is working again or not.

**Comment by narcolepticinsomniac** [comment]
It happens frequently, I just haven't been on Reddit much lately. It just happened, and when I checked, the iframe was already set to null. I reset it to null anyway, and it didn't fix anything. When it stops working I get a bunch of those same errors. I don't have any other extensions I'd consider buggy at the moment, but it's always a possibility there's a conflict. Still it'd be weird that it works, and then it doesn't.

It's not easy to repro on demand, and using a clean profile while I wait just isn't realistic. If you have any other checks to run when it occurs, just let me know. Otherwise, I'll have to hope you run into the same issue so you can figure it out. It is pretty annoying, unfortunately.

**Comment by narcolepticinsomniac** [comment]
Hey, Jeremy. You're good with this type of stuff, and you seem to enjoy it, so I figured I'd run something by you. As you probably noticed in my vids, I'm a fan of the extension Stylish. Well, I used to be anyway. A new dev took over a few months ago who seems determined to turn it into an inferior version of spyware. 

His updates have stripped functionality and he "partnered" with SimilarWeb which collects user browser history by default. Needless to say, none of this has been well received:

https://www.bleepingcomputer.com/news/software/2-million-users-impacted-by-new-data-collection-policy-in-stylish-browser-add-on/

https://forum.userstyles.org/discussion/53233/announcement-to-the-community

https://forum.userstyles.org/discussion/53048/release-notes-stylish-1-6-3-is-out#latest

There is a recently redone perfectly fine version sitting here at Github:

https://github.com/stylish-userstyles/stylish-chrome

It's GPL-3.0 so a few minor changes and a slight rebrand and it's good to go. The biggest hurdle for the person who decides to do it (somebody will soon) is database importation. It's an IndexedDB that is only compatible with the extension ID. Anyone who makes a successful alternative version will have to figure out the most user friendly way possible to import it.

Ideally, it'd be completely automated, but since Chrome extensions aren't allowed to play nice together, it might have to manually inserted somehow. Even just the import process is probably fairly complicated.

Anyway, I figured I'd see if you have any interest. I'm currently using an unpacked version of the one I linked. I should be good for the foreseeable future, but I know someone is going to do this, and I'm a fan, so I'm kinda hoping you might be into it. I'm a regular in the forum there and could definitely get the word out if you decide you're up for it.

**Comment by schomery** [comment]
Well, for exporting the DB, the only way is to convert the IndexedDB to a JSON object and then use `JSON.stringify` to actually copy the content. For sure this is going to be a manual thing as the current developer has not implemented it. But it is pretty straightforward to do it manually I guess.

 > Anyway, I figured I'd see if you have any interest

Well I havent looked at the code yet, but this project is not very small and it is going to take sometime to get familiar with it. I will take a look and update this post.

**Comment by narcolepticinsomniac** [comment]
Well, it's good news that you're considering it. I wouldn't be surprised if there are a few copycats of the previous version released in the near future, but I doubt any will bother to implement an import function. Practically anyone could release it "as is", but if the DB isn't easily importable, most people aren't gonna want to start from scratch. 

Unless a new dev is familiar to the community, you never know if their intentions are just as malicious as the current dev, not to mention, if they don't have the skills to fix/improve it, it won't last forever.

To get back to the YT ext. issue, it failed on the initial page-load on Reddit today. I checked the iframe in the console and it was "undefined". I set it to "null", but that had no effect. Reloading the page resolved it. 

I'm well aware that there's a high probability that another extension/script is interfering, so this info may or may not be at all helpful, but it was something new so I figured I'd let you know.

**Comment by schomery** [comment]
@narcolepticinsomniac I forked the project for now to see if we can have useful contribution. Let's see how it goes. You can open bugs in the project page if there is anything important for now to be resolved. Also I have added you as a collaborator so you can commit directly.

**Comment by narcolepticinsomniac** [comment]
Glad to hear it. A step in the right direction for Stylish, hopefully. Like I said, the version you forked was overhauled and modernized in the past couple years. It really was very good until the new dev got a hold of it. The main thing it'll need is a DB import, which may become easier in the next release. The new dev is rushing to put it out because of the negative reception he's gotten from butchering the functionality. On the Stylish extension page:

" Version 1.7.0 (coming soon) - Fixing bugs; Enabling style install through extension; Allowing sending feedback on specific styles, allowing backing up of installed styles."

He says it's coming in the next few days. Depending on how this new "backup" functionality is implemented, it may make it much simpler to export/import. 

Did you happen to come across the Ublock dev's analysis? 
https://www.ghacks.net/2017/01/04/major-stylish-add-on-changes-in-regards-to-privacy/#comment-4086083

I'm aware of a couple facts, which I can't elaborate on in good conscience, that leave little doubt that the new dev works for SimilarWeb. The whole backstory he posted and this new revelation that he just recently decided to partner with them for "technical support" is total BS. This is just another case of an analytics company buying a popular extension and turning it into spyware. Even worse, they're flat-out lying about the fact that they are actually the new owners.

While I, myself, will be very little help in terms of useful coding skills, I'm friendly with a couple of community members who could be. One of them is largely responsible for a lot of improvements made in the last big update. I know he had some cool new features mostly completed that got shot down for no good reason. He seemed to lose interest shortly after. I can let them know and see if they're interested. 

If you're going to post a version, once an import is worked out, the sooner the better. I have feeling it won't be long before others do the same. Probably not as well, and possibly with their own shady motivations.

I could work on some new logos/icons if you think it'd be important to change them.

**Comment by schomery** [comment]
@narcolepticinsomniac take a look at https://github.com/schomery/stylish-chrome/issues/1

**Comment by schomery** [comment]
> Did you happen to come across the Ublock dev's analysis

That's true; all the tracking codes are removed in https://github.com/schomery/stylish-chrome/commit/458daf0836c00be329b47522906d10fd449ff6b4 and https://github.com/schomery/stylish-chrome/commit/c1ab447130020358848a5afbff43c8c31de48269

**Comment by narcolepticinsomniac** [comment]
I think I may have finally figured out the conflict causing this issue. The failure to load YT vids seems to be directly related to certain hover previews being rendered by Imagus. In a clean profile with only YTOHP and Imagus enabled, try this page if you will:

https://www.reddit.com/r/gifs/comments/5p5hfj/obama_at_the_inauguration/dcoklff/?st=iy6g532s&sh=e626f4b2

Hover over the "JustHatch" first comment YT link. Works fine. Unload the iframe, and hover over the title link "Obama at the Inauguration", then go back to the same YT link in the first comment. It fails. Seems like when Imagus shows certain gifv's, for some reason or another it screws with YTOHP.

Something else weird? I can repro this pageload after pageload, but when I opened devtools to check for errors, once I reloaded the page with devtools open, it no longer happened.

**Comment by narcolepticinsomniac** [comment]
https://www.youtube.com/watch?v=w-McIdVuY88

**Comment by narcolepticinsomniac** [comment]
Another strange thing I came across while trying to pin down what was causing this, was a random YT link that just doesn't work at all on Reddit: https://www.reddit.com/r/gifs/comments/5p5hfj/obama_at_the_inauguration/dcoqjgn/?st=iy6iuxbl&sh=6226f708

Second comment "airhorn". I tested in a clean profile with only YTOHP enabled and it never works. Nothing strange about the URL, and if I post it here, it works. No clue. 

https://www.youtube.com/watch?v=w-McIdVuY88

**Comment by schomery** [comment]
> Another strange thing ...

Thanks! this one is fixed.

> I think I may have finally figured out the conflict causing this issue. ...

Well, I figured out what the problem is but I am not sure how to fix this! So basically when mouse is over a YouTube link, [L156](https://github.com/schomery/youtube-hover/blob/master/src/data/inject/index.js#L156) is called. It parses the YouTube link and if an ID is detected, the script waits for 1 seconds and then checks the active link one more time to make sure pointer is still over the link [L190](https://github.com/schomery/youtube-hover/blob/master/src/data/inject/index.js#L190)

So when you don't have this Imagus extension, `activeLink` works fine. But when Imagus is installed, sometimes their player is not getting unloaded and hence `activeLink` returns the Imagus player instead of the actual link. So the extension thinks the user pointer has been moved and hence no player is displayed.

I use [this code](https://github.com/schomery/youtube-hover/blob/master/src/data/inject/index.js#L190) to find the active element. I am not sure if there is an alternative method. To debug just insert
```js
console.log(link, activeLink)
```
before [L194](https://github.com/schomery/youtube-hover/blob/master/src/data/inject/index.js#L194)

**Comment by narcolepticinsomniac** [comment]
If you already know what the issue is, will me debugging really help at all? 

Short of trying to change the way you find the active element, could you maybe implement a workaround to fix their bug? Is it possible to reset `activeLink` on `mouseout` or `mouseleave`?

**Comment by schomery** [comment]
Well, we should find a way to detect the active element. Somehow a code that passes the actual active element and bypasses Imagus player ...

This one doesn't seem to do this
```js
activeLink = [...document.querySelectorAll(':hover')].pop();
```

**Comment by narcolepticinsomniac** [comment]
Hey Jeremy. I consulted the Imagus devs, and while they claimed to be unable to repro the issue, they were nice enough to recommend a different technique for getting the `activeLink`, [found here](http://pastebin.com/WbJFFzm5).

**Comment by schomery** [comment]
@narcolepticinsomniac I think this is fixed. Can you give the dev version a try?

**Comment by narcolepticinsomniac** [comment]
Seems good now, thanks.
